version: "3"

services:
  nginx:
    image: nginx:1.12-alpine
    restart: always
    depends_on:
      - app
    networks:
      - crosscloud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-data/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: syslog
      options:
        tag: nginx
  app:
    image: 767291032449.dkr.ecr.eu-central-1.amazonaws.com/crosscloud-enterprise:latest
    restart: always
    depends_on:
      - db
    networks:
      - crosscloud
    logging:
      driver: syslog
      options:
        tag: app
    environment:
      - "APP_ON_PREMISE=true"
      - "APP_ROOT=${APP_ROOT}"
      - "APP_UPDATE_CHANNEL=${APP_UPDATE_CHANNEL}"
      - "DATABASE_URL=postgres://crosscloud:@db/crosscloud"
      - "FORCE_HTTPS=true"
      - "MAILJET_API_KEY=${MAILJET_API_KEY}"
      - "MAILJET_API_SECRET=${MAILJET_API_SECRET}"
      - "MAILJET_SENDER_EMAIL=${MAILJET_SENDER_EMAIL}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "SMTP_SENDER_EMAIL=${SMTP_SENDER_EMAIL}"
      - "SMTP_URL=${SMTP_URL}"
  db:
    image: postgres:9.6
    restart: always
    networks:
      - crosscloud
    volumes:
     - /data/postgres:/var/lib/postgresql/data
    logging:
      driver: syslog
      options:
        tag: postgres

networks:
  crosscloud:
    driver: bridge
